### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: The Soft Stuff
email: jwrubel@gmail.com
description: "Openly-licensed job descriptions, interview questions, career ladders, tools and resources.

Like npm, but for technical managers and leaders."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#d6e2f3'
palette:
  dark: '#040707'
  grey: '#90969b'
  background: '#ffffff'
  callout: '#d6e2f3'
  alert: '#ed575b'
twitter_username: jameswrubel
github_username:  jwrubel
author: James Wrubel
logo: assets/images/softstufflogo.png
twitter:
  username: jameswrubel
social:
  name: James Wrubel
  links:
    - https://twitter.com/jameswrubel
    - https://github.com/jwrubel

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell: appKey
#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
