# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f5:9e:0f:82:19:74:75:f2:94:ce:98:11:78:37:1e:f3"
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - run:
          name: "bundle install"
          command: 'bundle install'
      - run:
          name: "npm install"
          command: 'npm install'
      - run:
          name: "build site"
          command: 'npm run-script build'
      - run: 'bash ./bin/deploy.sh'
